### ISSUE TITLE
Documented web usage doesn't work

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-js-processgraphs#6]
The Readme says:

> In a web environment you can include the library as follows:
> 
> ```html
> <script src="https://cdn.jsdelivr.net/npm/ajv@6.12/lib/ajv.min.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js"></script>
> ```

Putting those two lines into the `<head>` of a very simple HTML file gives me:

> Uncaught ReferenceError: require is not defined
> \<anonymous\> ajv.js:3
> ajv.js:3:20

**Comment by christophfriedrich** [comment]
If I replace the ajv URL with https://cdnjs.cloudflare.com/ajax/libs/ajv/6.12.5/ajv.bundle.js (as suggested by [their Readme](https://github.com/ajv-validator/ajv#using-in-browser)) (note the `bundle`), then that error message goes away.

But when trying to parse a process graph I instead get:

> Uncaught TypeError: s is not a constructor [main.min.js:1:3850]
    c https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    createJsonSchemaValidatorInstance https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    getJsonSchemaValidator https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    createProcessGraphInstance https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    createChildProcessGraph https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    parseNodeArguments https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    parse https://cdn.jsdelivr.net/npm/@openeo/js-processgraphs@1.0.0-beta.4/dist/main.min.js:1
    parse file:///home/christoph/dev/openeo-js-processgraphs/examples/list.html:15
    onclick file:///home/christoph/dev/openeo-js-processgraphs/examples/list.html:1

**Comment by m-mohr** [comment]
Could you please provide the repro example? :-)

**Comment by christophfriedrich** [comment]
As discussed in person, it was indeed a simple lower/upper case error... :roll_eyes:

**Comment by christophfriedrich** [comment]
For future reference: The repro example I was using was exactly this script: https://github.com/Open-EO/openeo-js-processgraphs/blob/13974e8d769f3e668c9d612cd468f1abb0fc2a30/examples/browser.html#L1-L34

executed with the response of https://earthengine.openeo.org/v1.0/processes and [the Earth Engine driver sample process graph](https://github.com/Open-EO/openeo-earthengine-driver/blob/0f5f094de2a3802d85d47b79862c127b862a9c56/tests/data/sample-processgraph.json).
